# This playbook takes care of installing the apache and host our own website
---
- hosts: localhost
  tasks:

    - name: Install package
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - apache2
        - nginx
        - unzip
      become: true